input.onButtonPressed(Button.A, function () {
    basic.pause(2000)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
    music.playMelody("C5 B A G F E D C ", 120)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 255)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 255)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 255)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    maqueen.motorStop(maqueen.Motors.All)
})
input.onButtonPressed(Button.B, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
})
let strip: neopixel.Strip = null
basic.showIcon(IconNames.Happy)
strip = neopixel.create(DigitalPin.P1, 4, NeoPixelMode.RGB)
basic.forever(function () {
	
})
